Remove wercker, use sd to publish
screwdriver-cd/datastore-dynamodb pull request #28
Opened 2016-10-06 21:09 UTC by d2lam

Use screwdriver instead :d2celebrate:

2016-10-06 21:37 UTC, petey requested changes

2016-10-06 21:37 UTC, petey commented on README.md
> +[![Version][npm-image]][npm-url] ![Downloads][downloads-image][![Open Issues][issues-image]][issues-url] [![Dependency Status][daviddm-image]][daviddm-url] ![License][license-image]
Now there is no build status badge? 

![status](https://cd.screwdriver.cd/pipelines/8e6fcf447ebd13f5cfbdb570e382ad8c410c2ec0/badge)

2016-10-06 21:51 UTC, d2lam commented on README.md
> +[![Version][npm-image]][npm-url] ![Downloads][downloads-image][![Open Issues][issues-image]][issues-url] [![Dependency Status][daviddm-image]][daviddm-url] ![License][license-image]
Fixed

2016-10-06 23:32 UTC, petey approved these changes

2016-10-06 23:32 UTC, petey commented
👍

2016-10-07 18:50 UTC, minzcmu approved these changes
👍

2016-10-07 18:50 UTC, merged